
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='mate3',
    version='0.5.0',
    description='Outback Mate3s Python Library',
    python_requires='==3.*,>=3.7.0',
    project_urls={"homepage": "https://github.com/adamcharnock/mate3/", "repository": "https://github.com/adamcharnock/mate3/"},
    author='Adam Charnock',
    author_email='adam@adamcharnock.com',
    entry_points={"console_scripts": ["mate3 = mate3.main:main"]},
    packages=[],
    package_dir={"": "."},
    package_data={},
    install_requires=['loguru==0.*,>=0.5.3', 'pymodbus==2.*,>=2.4.0'],
    extras_require={"dev": ["black==18.*,>=18.3.0.a0", "dephell>=0.7.6", "pytest==6.*,>=6.2.1"]},
)
