
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='mate3',
    version='0.3.0',
    python_requires='==3.*,>=3.7.0',
    author='Adam Charnock',
    author_email='adam@adamcharnock.com',
    entry_points={'console_scripts': ['mate3 = mate3.main:main', 'mate3_write = mate3.mate3_write:main', 'mate3_pg = mate3.mate3_pg:main']},
    packages=['mate3'],
    package_data={},
    install_requires=['pymodbus==2.*,>=2.2.0'],
    extras_require={'dev': ['black==18.*,>=18.3.0', 'camelot-py==0.*,>=0.7.3', 'dephell>=0.7.6', 'excalibur-py==0.*,>=0.4.2', 'fissix==19.2b1', 'pytest==3.*,>=3.0.0'], 'mate3_pg': ['psycopg2==2.*,>=2.8.3', 'pyyaml==5.*,>=5.1.2']},
)
